# Generated by Django 3.2.3 on 2021-07-21 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipe',
            new_name='recipient',
        ),
    ]
